"""
Django settings for ar_museum_project project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import mimetypes
import os
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent

# .env dosyasını yükle
load_dotenv(BASE_DIR / '.env')

# Boto3/Botocore checksum uyuşmazlığından kaynaklı MissingContentLength hatasını çözmek için
os.environ['AWS_REQUEST_CHECKSUM_CALCULATION'] = 'when_required'
os.environ['AWS_RESPONSE_CHECKSUM_VALIDATION'] = 'when_required'

mimetypes.add_type("model/gltf-binary", ".glb", True)
mimetypes.add_type("model/vnd.usdz+zip", ".usdz", True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-2_cy3hn%osnh!-bfnp8(^d)gj+xyudoqn=#1b7*dlnfx4a71g4")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "True").lower() in ("true", "1", "t")

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        "DJANGO_ALLOWED_HOSTS",
        "test.ugurgulaydin.com.tr,www.ugurgulaydin.com.tr,ugurgulaydin.com.tr,127.0.0.1,localhost"
    ).split(",")
    if host.strip()
]

# Cloudflare arkasinda calistigi icin HTTPS yonlendirmesini anlamasi saglanir
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "DJANGO_CSRF_TRUSTED_ORIGINS",
        "https://test.ugurgulaydin.com.tr,https://www.ugurgulaydin.com.tr,https://ugurgulaydin.com.tr,https://s3.ugurgulaydin.com.tr,http://127.0.0.1:8000,http://localhost:8000"
    ).split(",")
    if origin.strip()
]


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "storages",
    "artifacts",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "ar_museum_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "ar_museum_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "ar_museum"),
        "USER": os.getenv("DB_USER", "postgres"),
        "PASSWORD": os.getenv("DB_PASSWORD", ""),
        "HOST": os.getenv("DB_HOST", "127.0.0.1"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "tr"

TIME_ZONE = "Europe/Istanbul"

USE_I18N = True

USE_TZ = True

X_FRAME_OPTIONS = 'SAMEORIGIN'



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# MinIO S3 Settings
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME", 'ar-museum')
AWS_S3_ENDPOINT_URL = os.getenv("AWS_S3_ENDPOINT_URL", 'https://s3.ugurgulaydin.com.tr')
AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME", 'us-east-1') # Bölge tespiti hatasını (403) engellemek için zorunludur
AWS_S3_FILE_OVERWRITE = True # HeadObject hatasını engellemek için True olmalıdır
AWS_QUERYSTRING_AUTH = False
AWS_S3_VERIFY = True # Re-enabling as Cloudflare has valid SSL
AWS_DEFAULT_ACL = None # ACL kaynaklı 403 yetki hatalarını önlemek için None olmalıdır
AWS_S3_SIGNATURE_VERSION = 's3v4' # Bölge uyuşmazlığı ve imza hatasını (403) önlemek için stabil v4 imza sürümü
AWS_S3_MAX_MEMORY_SIZE = 100 * 1024 * 1024

# Disable multipart for files up to 1GB to ensure Content-Length is sent correctly
from boto3.s3.transfer import TransferConfig
AWS_S3_TRANSFER_CONFIG = TransferConfig(
    multipart_threshold=1024 * 1024 * 1024, 
    max_concurrency=10
)

# Optimized config for MinIO behind a proxy
AWS_S3_CONFIG = {
    'parameter_validation': False,
    'request_checksum_calculation': 'when_required',
    'response_checksum_validation': 'when_required',
    's3': {
        'addressing_style': 'path',
    },
}

# Media files storage (Models and Images)
STORAGES = {
    "default": {
        "BACKEND": "artifacts.storage.ARS3Storage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Note: MEDIA_URL is still used for relative path construction in some Django features
AWS_S3_PUBLIC_URL = os.getenv("AWS_S3_PUBLIC_URL")
if AWS_S3_PUBLIC_URL:
    MEDIA_URL = f'{AWS_S3_PUBLIC_URL}/{AWS_STORAGE_BUCKET_NAME}/'
else:
    MEDIA_URL = f'{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Trigger reload to register new static directory

JAZZMIN_SETTINGS = {
    "site_title": "AR Müzesi Yönetimi",
    "site_header": "AR Müzesi",
    "site_brand": "AR Müzesi",
    "site_icon": None,
    "welcome_sign": "AR Müzesi Yönetim Paneline Hoş Geldiniz",
    "copyright": "AR Müzesi Ltd",
    "search_model": ["artifacts.Artifact"],
    "user_avatar": None,
    "topmenu_links": [
        {"name": "Kontrol Paneli",  "url": "admin:index", "permissions": ["auth.view_user"]},
        {"model": "artifacts.Artifact"},
    ],
    "usermenu_links": [],
    "custom_links": {
        "artifacts": [
            {
                "name": "İşlem Günlükleri",
                "url": "/admin/logs/",
                "icon": "fas fa-history",
            }
        ]
    },
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["artifacts", "auth"],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.group": "fas fa-users",
        "artifacts.artifact": "fas fa-landmark",
        "artifacts.reconstructionsession": "fas fa-camera",
        "artifacts.sessionimage": "fas fa-image",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "collapsible"},
    "custom_css": "css/custom_admin_v2.css",
    "custom_js": "js/custom_admin_v2.js",
}


JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_color": "navbar-dark bg-dark",
    "accent": "accent-warning",
    "navbar": "navbar-dark bg-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-warning",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "flatly",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-warning",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}


