# Generated by Django 6.0.1 on 2026-01-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Eser Adı")),
                ("description", models.TextField(verbose_name="Detaylı Açıklama")),
                (
                    "image",
                    models.ImageField(
                        upload_to="artifacts/images/", verbose_name="Kapak Görseli"
                    ),
                ),
                (
                    "model_3d",
                    models.FileField(
                        upload_to="artifacts/models/",
                        verbose_name="3D Model (GLB/GLTF)",
                    ),
                ),
                (
                    "model_ios",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="artifacts/models/",
                        verbose_name="iOS AR Modeli (USDZ)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Eser",
                "verbose_name_plural": "Eserler",
                "ordering": ["-created_at"],
            },
        ),
    ]
