# Generated by Django 5.2.7 on 2026-04-18 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artifacts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReconstructionSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Oturum Adı")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Bekliyor"),
                            ("processing", "İşleniyor"),
                            ("completed", "Tamamlandı"),
                            ("failed", "Hata Oluştu"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "result_artifact",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reconstruction_session",
                        to="artifacts.artifact",
                    ),
                ),
            ],
            options={
                "verbose_name": "3D Tarama Oturumu",
                "verbose_name_plural": "3D Tarama Oturumları",
            },
        ),
        migrations.CreateModel(
            name="SessionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="reconstructions/images/")),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="artifacts.reconstructionsession",
                    ),
                ),
            ],
        ),
    ]
