# Generated by Django 5.2.6 on 2026-06-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artifacts", "0002_reconstructionsession_sessionimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="reconstructionsession",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Açıklama"),
        ),
    ]
